name: post_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 国际化
    sdk: flutter
  crypto: ^3.0.2
  # 全局状态管理
  provider:
  # 文件读写
  path_provider: 2.0.15
  # 网络请求
  dio: ^5.3.2
  json_annotation:
  #svg图标
  flutter_svg: 2.0.7
  #图表
  fl_chart: 0.63.0
  #操作磁盘上存储位置的方法集
  path:
  #sqlite(支持android，ios，macos)
  sqflite:
  #sqlite(支持windows，linux)
  sqflite_common_ffi:
  sqflite_common_ffi_web:
  #列表刷新
  easy_refresh: 3.3.2+1
  #文件选择
  file_picker: 5.3.3
  # Flutter Quill Packages
  flutter_quill: ^9.3.4
  dart_quill_delta: ^9.3.4
  flutter_quill_extensions: ^9.3.4
  flutter_quill_test: ^9.3.4
  quill_html_converter: ^9.3.4
  quill_pdf_converter: ^9.3.4
  # websocket
  web_socket_channel: ^2.4.4
  audioplayers:
  audio_video_progress_bar:
  just_audio:
  just_audio_windows:
  just_audio_mpv:
  # 媒体
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.
  #  media_kit: ^1.1.3
  #  # 视频播放
  #  media_kit_video: ^1.1.3
  #  media_kit_native_event_loop: ^1.0.7
  #  media_kit_libs_android_video: ^1.3.1
  #  media_kit_libs_ios_video: ^1.1.2
  #  media_kit_libs_macos_video: ^1.1.2
  #  media_kit_libs_windows_video: ^1.0.6
  #  media_kit_libs_linux: ^1.1.0
  intl:
  #网格
  flutter_staggered_grid_view:
  #图片操作工具
  image: ^4.0.17
  #  flutter_webrtc: ^0.10.4
  livekit_client: 2.1.4
  flutter_background: ^1.0.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

